services:
  - type: web
    name: soluciona-ya
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: soluciona-ya-db
          property: connectionString

databases:
  - name: soluciona-ya-db
    databaseName: solucionaya
    plan: free
